# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'peers_gui_client.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from pyqtgraph import PlotWidget

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1295, 738)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 160, 228))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.ConnectButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.ConnectButton.setObjectName("ConnectButton")
        self.verticalLayout.addWidget(self.ConnectButton)
        self.DisconnectButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.DisconnectButton.setObjectName("DisconnectButton")
        self.verticalLayout.addWidget(self.DisconnectButton)
        self.NewAnchorsButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.NewAnchorsButton.setObjectName("NewAnchorsButton")
        self.verticalLayout.addWidget(self.NewAnchorsButton)
        self.RelateToMastersButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.RelateToMastersButton.setObjectName("RelateToMastersButton")
        self.verticalLayout.addWidget(self.RelateToMastersButton)
        self.ConfigureButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.ConfigureButton.setObjectName("ConfigureButton")
        self.verticalLayout.addWidget(self.ConfigureButton)
        self.StartButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.StartButton.setObjectName("StartButton")
        self.verticalLayout.addWidget(self.StartButton)
        self.StopButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.StopButton.setObjectName("StopButton")
        self.verticalLayout.addWidget(self.StopButton)
        self.StateRequestButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.StateRequestButton.setObjectName("StateRequestButton")
        self.verticalLayout.addWidget(self.StateRequestButton)
        self.BeepLabel = QtWidgets.QLabel(self.centralwidget)
        self.BeepLabel.setGeometry(QtCore.QRect(170, 0, 1111, 16))
        self.BeepLabel.setObjectName("BeepLabel")
        self.floor_map = PlotWidget(self.centralwidget)
        self.floor_map.setGeometry(QtCore.QRect(170, 30, 1101, 641))
        self.floor_map.setObjectName("floor_map")
        self.AddObjButton = QtWidgets.QPushButton(self.centralwidget)
        self.AddObjButton.setGeometry(QtCore.QRect(40, 290, 75, 23))
        self.AddObjButton.setObjectName("AddObjButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1295, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ConnectButton.setText(_translate("MainWindow", "Connect"))
        self.DisconnectButton.setText(_translate("MainWindow", "Disconnect"))
        self.NewAnchorsButton.setText(_translate("MainWindow", "Send Anchors"))
        self.RelateToMastersButton.setText(_translate("MainWindow", "Relate to masters"))
        self.ConfigureButton.setText(_translate("MainWindow", "Configure"))
        self.StartButton.setText(_translate("MainWindow", "Start"))
        self.StopButton.setText(_translate("MainWindow", "Stop"))
        self.StateRequestButton.setText(_translate("MainWindow", "State Request"))
        self.BeepLabel.setText(_translate("MainWindow", "TextLabel"))
        self.AddObjButton.setText(_translate("MainWindow", "Add obj"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
